apiVersion: v1
kind: Service
metadata:
  name: bank-backend-service
  namespace: banking-app
spec:
  selector:
    app: bank-backend  # This should match deployment labels
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP